### ISSUE TITLE
Automatically generate :on_delete and :on_update

### ISSUE THREAD

**Issue by jtomaszewski** [jenseng/immigrant#18]
Have you thought about automatically generating the `:on_delete` and `:on_update` [options](http://api.rubyonrails.org/v4.2.0/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_foreign_key)?

For example:
```rb
# models/user.rb
has_many :images, dependent: :delete

# migration
add_foreign_key "users", "images", on_delete: :cascade
```

Not a "must" feature, but a nice-to-have one, I think so.

**Comment by jenseng** [comment]
:thumbsup: it's actually [implemented for `on_delete:`](https://github.com/jenseng/immigrant/blob/master/test/immigrant_test.rb#L103), but only in a foreigner-compatible way (it sets the `:on_delete` value to `:delete` instead of `:cascade`) ... so we should fix that for rails 4.2, and also implement it for `:on_update` as well
