### ISSUE TITLE
Generated migration does not consider dependent: :destroy

### ISSUE THREAD

**Issue by DannyBen** [jenseng/immigrant#24]
Not sure if its an issue or a question more suitable for StackOverflow.

I have read the issues #18 and #20 so I figured maybe here is a good place to write.

* I am using Rails 4.2.3 
* I have added the immigrant gem, without adding the foreigner gem.
* My models have statements like `has_many :invitations, dependent: :nullify` and `has_many :events, dependent: :destroy`
* After generating immigrant migrations, it generated all the `add_foreign_key` but without anything (`on_delete` or `dependent` ?... ) to reflect these dependencies.

So now, all my tests fail with `update or delete on table "groups" violates foreign key constraint "steps_group_id_fk" on table "steps"`

Have I missed a step? Or is this an issue?

**Comment by jenseng** [comment]
Immigrant does currently handle `dependent: :delete`, but I don't think it needs to handle `dependent: :destroy`, since you're basically saying "when I delete this thing, I want Rails to call destroy on each dependent model" (which could then trigger AR callbacks, etc.). So it may be unsafe/undesirable for a foreign key to cascade, if you somehow deleted the parent object via `delete_all` or whatever.

That said, Immigrant probably should handle `dependent: :nullify`. So we can keep this ticket open to address it.

For your particular testing issue though, it might have more to do with your code and how you're cleaning up data. Like maybe you've got a `Group.delete_all` that you could change to a `Group.destroy_all`? Or if you're just cleaning up all the things between tests, you might consider a different strategy. For example, [DatabaseCleaner](https://github.com/DatabaseCleaner/database_cleaner) works well for this, and will do a single `TRUNCATE` statement with all the tables, so you don't have to worry about foreign keys.
